export const FETCH_NEWS_REQUEST_START = 'FETCH_NEWS_REQUEST_START';
export const FETCH_NEWS_REQUEST_COMPLETED = 'FETCH_NEWS_REQUEST_COMPLETED';
export const DEL_NEWS_REQUEST_START = 'DEL_NEWS_REQUEST_START';
export const DEL_NEWS_REQUEST_COMPLETED = 'DEL_NEWSR_REQUEST_COMPLETED';